# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('move', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameId',
            field=models.TextField(),
        ),
    ]
